
export default [
    {
        "category":true,
        "children":[
            {
                "category":true,
                "children":[
                    {
                        "category":true,
                        "children":[
                            {
                                "category":true,
                                "children":[],
                                "classes":"",
                                "expanded":false,
                                "hasChildren":false,
                                "href":"",
                                "id":"testQueue",
                                "pid":"Local",
                                "text":"testQueue"
                            }
                        ],
                        "classes":"",
                        "expanded":true,
                        "hasChildren":false,
                        "href":"",
                        "id":"Local",
                        "pid":"Queue",
                        "text":"本地队列"
                    },
                    {
                        "category":true,
                        "children":[
                            {
                                "category":true,
                                "children":[],
                                "classes":"",
                                "expanded":false,
                                "hasChildren":false,
                                "href":"",
                                "id":"test",
                                "pid":"Remote",
                                "text":"test"
                            }
                        ],
                        "classes":"",
                        "expanded":true,
                        "hasChildren":false,
                        "href":"",
                        "id":"Remote",
                        "pid":"Queue",
                        "text":"远程队列"
                    }
                ],
                "classes":"",
                "expanded":true,
                "hasChildren":false,
                "href":"",
                "id":"Queue",
                "pid":"1",
                "text":"队列"
            },
            {
                "category":true,
                "children":[
                    {
                        "category":true,
                        "children":[

                        ],
                        "classes":"",
                        "expanded":false,
                        "hasChildren":false,
                        "href":"",
                        "id":"xhh1",
                        "pid":"Topic",
                        "text":"xhh1"
                    },
                    {
                        "category":true,
                        "children":[

                        ],
                        "classes":"",
                        "expanded":false,
                        "hasChildren":false,
                        "href":"",
                        "id":"xhh",
                        "pid":"Topic",
                        "text":"xhh"
                    },
                    {
                        "category":true,
                        "children":[

                        ],
                        "classes":"",
                        "expanded":false,
                        "hasChildren":false,
                        "href":"",
                        "id":"testTopic",
                        "pid":"Topic",
                        "text":"testTopic"
                    }
                ],
                "classes":"",
                "expanded":true,
                "hasChildren":false,
                "href":"",
                "id":"Topic",
                "pid":"1",
                "text":"主题"
            }
        ],
        "classes":"category",
        "expanded":false,
        "hasChildren":true,
        "href":"",
        "id":"1",
        "pid":"0",
        "text":"可用阅读者"
    }
]




